services:
  db:
    image: postgres:15-alpine
    container_name: erp_service_db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - erp_shared_network
    shm_size: 1gb
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: postgres -c max_connections=500
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:8080" # наружу выброшен 8081, потому что на 8080 висит бот. Имейте в виду при изменении
    networks:
      - erp_shared_network
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes # Включаем AOF для сохранения FSM и ключей
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - erp_shared_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - erp_shared_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - erp_shared_network
    volumes:
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - erp_logs_volume:/var/log/backend
    command: -config.file=/etc/promtail/config.yml
    networks:
      - erp_shared_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - erp_shared_network
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  loki_data:
  grafana_data:
  erp_logs_volume:
    name: erp_logs_volume

networks:
  erp_shared_network:
    name: erp_shared_network
    driver: bridge